SELECT * FROM `buildings`
SELECT * FROM `buildings_has_resources`
SELECT * FROM `maps`
SELECT * FROM `maps_has_buildings`
SELECT * FROM `maps_has_objectives`
SELECT * FROM `maps_has_resources`
SELECT * FROM `objectives`
SELECT * FROM `players`
SELECT * FROM `quests`
SELECT * FROM `resources`
SELECT * FROM `teams`
SELECT * FROM `teams_has_players`
SELECT * FROM `teams_has_troops`
SELECT * FROM `troops`
SELECT * FROM `troops_has_quests`
SELECT * FROM `troops_has_resources`
SELECT * FROM `troops_has_weapons`
SELECT * FROM `weapons`
SELECT * FROM `weapons_has_resources`